FROM node:22-alpine AS build

WORKDIR /usr/src/app

ARG VITE_PHP_API_URL=http://localhost:8000
ARG VITE_NODE_API_URL=http://localhost:3000

ENV VITE_PHP_API_URL=${VITE_PHP_API_URL}
ENV VITE_NODE_API_URL=${VITE_NODE_API_URL}

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80
